# Generated by Django 5.1.2 on 2024-10-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlists',
        ),
    ]
